### ISSUE TITLE
Rename class base

### ISSUE THREAD

**Issue by painna** [EtheaDev/DBAwareLabeledComponents#1]
Estou tendo problemas ao tentar instalar no Delphi 10.3, pois já existem componentes com o nome base TLabeledDBEdit, seria possivel uma mudança na nomenclatura para tipo TLabeledDBADBEdit por exemplo para evitar conflitos com componentes mais antigos?
Algum package para Delphi 10.1 Berlin ??

Grato.

**Comment by carloBarazzetta** [comment]
Please write in english...
I cannot rename my component, consider to replace the old TLabeledDBEdit component.
Packages for Delphi 10.1 added today into 1.2 version.
