### ISSUE TITLE
Error adding TLaberedNumberbox to a form

### ISSUE THREAD

**Issue by FranciscoGarciaGonzalez** [EtheaDev/DBAwareLabeledComponents#4]
Error when adding tlabelednumberbox to a form.

Error GetEditControlFont: Control Class TLabeledNumberBox not accepted.

![image](https://github.com/EtheaDev/DBAwareLabeledComponents/assets/55201686/76376044-a452-4754-9c51-15b17355c4bd)

**Comment by carloBarazzetta** [comment]
Sorry, I'll investigate as soon as possible...

**Comment by FranciscoGarciaGonzalez** [comment]
thanks,
is strange, only fail with TLabeledNumberBox, with TLabeledDBNumberBox all is ok.

**Comment by FranciscoGarciaGonzalez** [comment]
olé, Grazie mille
